In [ ]:
import torch

# temp = torch.tensor(list(range(9)))
temp = torch.Tensor(list(range(9)))
print(f'{temp.type()}')
temp

torch.FloatTensor


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
temp.sqrt()

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])

In [ ]:
temp.cos()

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])