In [81]:
from google.colab import drive
drive.mount('/content/drive')

# from skimage.transform import resize
# from skimage.color import rgb2gray
import matplotlib.pyplot as plt
import numpy as np
import torch
import imageio


device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [82]:
red_dir = "/content/drive/My Drive/ECGR4090-RealTimeAI/hw2/red.jpg"
green_dir = "/content/drive/My Drive/ECGR4090-RealTimeAI/hw2/green.jpg"
blue_dir = "/content/drive/My Drive/ECGR4090-RealTimeAI/hw2/blue.jpg"


In [83]:
red_img = imageio.imread(red_dir)
print("NumPy: ", type(red_img))
print("Shape: ", red_img.shape)
print("dtype: ", red_img.dtype)

red_img_np = torch.from_numpy(red_img)
print('Mean value: ', torch.mean(red_img_np.float()) )

print(red_img)

NumPy:  <class 'imageio.core.util.Array'>
Shape:  (244, 432, 3)
dtype:  uint8
Mean value:  tensor(136.5813)
[[[206 222 245]
  [207 223 246]
  [207 223 246]
  ...
  [167 209 247]
  [168 210 248]
  [167 211 248]]

 [[206 222 245]
  [206 222 245]
  [206 222 245]
  ...
  [162 206 243]
  [161 205 242]
  [161 205 242]]

 [[206 222 245]
  [206 222 245]
  [206 222 245]
  ...
  [156 201 240]
  [156 201 240]
  [155 200 239]]

 ...

 [[114 113 118]
  [115 114 120]
  [115 114 120]
  ...
  [127 123 124]
  [131 127 128]
  [128 124 125]]

 [[114 113 118]
  [117 116 121]
  [120 119 125]
  ...
  [128 124 125]
  [131 127 128]
  [129 125 126]]

 [[126 125 130]
  [130 129 134]
  [133 132 137]
  ...
  [128 124 125]
  [130 126 127]
  [134 130 131]]]


In [86]:
blue_img = imageio.imread(blue_dir)
print("NumPy: ", type(blue_img))
print("Shape: ", blue_img.shape)
print("dtype: ", blue_img.dtype)

blue_img_np = torch.from_numpy(blue_img)
print('Mean value: ', torch.mean(blue_img_np.float()) )

print(blue_img)

NumPy:  <class 'imageio.core.util.Array'>
Shape:  (740, 710, 3)
dtype:  uint8
Mean value:  tensor(85.5420)
[[[195 191 188]
  [195 191 188]
  [195 191 188]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[195 191 188]
  [195 191 188]
  [195 191 188]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[194 190 187]
  [195 191 188]
  [195 191 188]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 91  77  64]
  [ 82  68  55]
  [ 84  70  57]
  ...
  [ 93  54  25]
  [ 89  54  26]
  [ 87  53  25]]

 [[ 94  80  67]
  [ 84  70  57]
  [ 86  72  59]
  ...
  [ 86  51  21]
  [ 84  50  22]
  [ 81  50  21]]

 [[ 90  76  63]
  [ 83  69  56]
  [ 86  72  59]
  ...
  [ 82  49  18]
  [ 77  48  18]
  [ 74  47  17]]]


In [85]:
green_img = imageio.imread(green_dir)
print("NumPy: ", type(green_img))
print("Shape: ", green_img.shape)
print("dtype: ", green_img.dtype)

green_img_np = torch.from_numpy(green_img)
print('Mean value: ', torch.mean(green_img_np.float()) )

print(green_img)

NumPy:  <class 'imageio.core.util.Array'>
Shape:  (300, 300, 3)
dtype:  uint8
Mean value:  tensor(151.3759)
[[[194 193 188]
  [194 193 188]
  [194 193 188]
  ...
  [185 186 180]
  [185 186 180]
  [185 186 180]]

 [[194 193 188]
  [194 193 188]
  [194 193 188]
  ...
  [185 186 180]
  [185 186 180]
  [185 186 180]]

 [[194 193 188]
  [194 193 188]
  [194 193 188]
  ...
  [185 186 180]
  [185 186 180]
  [185 186 180]]

 ...

 [[197 197 187]
  [198 198 188]
  [198 198 188]
  ...
  [196 195 190]
  [196 195 190]
  [195 194 189]]

 [[197 197 187]
  [198 198 188]
  [199 199 189]
  ...
  [197 196 191]
  [197 196 191]
  [197 196 191]]

 [[198 198 188]
  [198 198 188]
  [199 199 189]
  ...
  [200 197 192]
  [200 197 192]
  [199 196 191]]]
